package Telas;

import dal.ModuloConexao;
import java.awt.Color;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Locale;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;

    public TelaPrincipal() {
        initComponents();

        conexao = ModuloConexao.conector();
        aparencia();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        buttonGroup2 = new javax.swing.ButtonGroup();
        ImageIcon icon = new ImageIcon(getClass().getResource("/icones/FundoDesktop.png"));
        final Image image = icon.getImage();
        desktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        btnCadastroCliente = new javax.swing.JToggleButton();
        btnCadastraOS = new javax.swing.JToggleButton();
        btnCadastroUsuario = new javax.swing.JToggleButton();
        btnRelatorioCliente = new javax.swing.JToggleButton();
        btnRelatorioServ = new javax.swing.JToggleButton();
        pnlRelatorio = new javax.swing.JPanel();
        btnRelatoriosAll = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        btnAjuda = new javax.swing.JToggleButton();
        btnAjudaSobre = new javax.swing.JToggleButton();
        btnOpTrocar = new javax.swing.JToggleButton();
        btnOpSair = new javax.swing.JToggleButton();
        jPanel9 = new javax.swing.JPanel();
        btnOptionAll = new javax.swing.JToggleButton();
        btnTec = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        pnlCadastrar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarAll = new javax.swing.JToggleButton();

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Help Desk");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desktop.setBackground(new java.awt.Color(153, 68, 72));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 0, 1014, 630));

        btnCadastroCliente.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        buttonGroup1.add(btnCadastroCliente);
        btnCadastroCliente.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnCadastroCliente.setText("Cliente");
        btnCadastroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 182, 166, 40));

        btnCadastraOS.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        buttonGroup1.add(btnCadastraOS);
        btnCadastraOS.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnCadastraOS.setText("Ordem de Serviço");
        btnCadastraOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastraOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraOSActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastraOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 166, 40));

        btnCadastroUsuario.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        buttonGroup1.add(btnCadastroUsuario);
        btnCadastroUsuario.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnCadastroUsuario.setText("Usuário");
        btnCadastroUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 262, 166, 40));

        btnRelatorioCliente.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        buttonGroup1.add(btnRelatorioCliente);
        btnRelatorioCliente.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnRelatorioCliente.setText("Cliente");
        btnRelatorioCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorioCliente.setPreferredSize(new java.awt.Dimension(166, 40));
        btnRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 355, -1, -1));

        btnRelatorioServ.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        buttonGroup1.add(btnRelatorioServ);
        btnRelatorioServ.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnRelatorioServ.setText("Serviços");
        btnRelatorioServ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelatorioServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioServActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorioServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 395, 166, 40));

        pnlRelatorio.setBackground(new java.awt.Color(153, 68, 72));
        pnlRelatorio.setPreferredSize(new java.awt.Dimension(166, 53));
        pnlRelatorio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRelatoriosAll.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        buttonGroup2.add(btnRelatoriosAll);
        btnRelatoriosAll.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnRelatoriosAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Relatorio.png"))); // NOI18N
        btnRelatoriosAll.setText("Relatórios");
        btnRelatoriosAll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRelatoriosAll.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRelatoriosAll.setPreferredSize(new java.awt.Dimension(166, 53));
        btnRelatoriosAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatoriosAllActionPerformed(evt);
            }
        });
        pnlRelatorio.add(btnRelatoriosAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 302, -1, -1));

        jPanel8.setBackground(new java.awt.Color(153, 68, 72));
        jPanel8.setPreferredSize(new java.awt.Dimension(166, 45));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAjuda.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        buttonGroup2.add(btnAjuda);
        btnAjuda.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Help.png"))); // NOI18N
        btnAjuda.setText("Ajuda");
        btnAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAjuda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaActionPerformed(evt);
            }
        });
        jPanel8.add(btnAjuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 166, 45));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 435, -1, -1));

        btnAjudaSobre.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        btnAjudaSobre.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnAjudaSobre.setText("Sobre");
        btnAjudaSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjudaSobre.setPreferredSize(new java.awt.Dimension(57, 27));
        btnAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjudaSobreActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjudaSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 166, 34));

        btnOpTrocar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        btnOpTrocar.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnOpTrocar.setText("Trocar Usuário");
        btnOpTrocar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpTrocar.setPreferredSize(new java.awt.Dimension(57, 27));
        btnOpTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpTrocarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpTrocar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 559, 166, 34));

        btnOpSair.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        btnOpSair.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnOpSair.setText("Sair");
        btnOpSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 593, 166, 34));

        jPanel9.setBackground(new java.awt.Color(153, 68, 72));
        jPanel9.setPreferredSize(new java.awt.Dimension(166, 45));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOptionAll.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        buttonGroup2.add(btnOptionAll);
        btnOptionAll.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        btnOptionAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Help.png"))); // NOI18N
        btnOptionAll.setText("Opções");
        btnOptionAll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOptionAll.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnOptionAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionAllActionPerformed(evt);
            }
        });
        jPanel9.add(btnOptionAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 166, 45));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 514, -1, -1));

        btnTec.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        btnTec.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnTec.setText("Técnico");
        btnTec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTecActionPerformed(evt);
            }
        });
        getContentPane().add(btnTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 166, 40));

        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 68, 72));
        jLabel4.setText("Help Desk");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/icons8-coroa-50.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(224, 204, 149));
        jPanel3.setMinimumSize(new java.awt.Dimension(160, 579));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/user.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 130, -1));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuário");
        jPanel3.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 130, -1));

        lblPerfil.setBackground(java.awt.Color.white);
        lblPerfil.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        lblPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerfil.setText("Perfil");
        jPanel3.add(lblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 130, -1));

        lblData.setBackground(java.awt.Color.white);
        lblData.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setText("Data");
        jPanel3.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 130, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 130, 630));

        pnlCadastrar.setBackground(new java.awt.Color(153, 68, 72));
        pnlCadastrar.setPreferredSize(new java.awt.Dimension(166, 53));
        pnlCadastrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastros");
        pnlCadastrar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, -1, -1));

        btnCadastrarAll.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.focus"));
        buttonGroup2.add(btnCadastrarAll);
        btnCadastrarAll.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnCadastrarAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Cadastrar.png"))); // NOI18N
        btnCadastrarAll.setText("Cadastrar");
        btnCadastrarAll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCadastrarAll.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadastrarAll.setPreferredSize(new java.awt.Dimension(166, 53));
        btnCadastrarAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarAllActionPerformed(evt);
            }
        });
        pnlCadastrar.add(btnCadastrarAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));
        pnlCadastrar.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Substitui a label lblData por data atual do Sistema .
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));

    }//GEN-LAST:event_formWindowActivated

    private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClienteActionPerformed
// Abre o Form TelaCliente dentro do desktop pane
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        desktop.add(cliente);


        
        
        
    }//GEN-LAST:event_btnCadastroClienteActionPerformed

    private void btnCadastraOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraOSActionPerformed
// Abre o form TelaOrdemDeServiço dentro do desktop pane
        TelaOrdemDeServico os = new TelaOrdemDeServico();
        os.setVisible(true);
        desktop.add(os);
    }//GEN-LAST:event_btnCadastraOSActionPerformed

    private void btnCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroUsuarioActionPerformed
// Abre o Form TelaUsuario dentro do desktop pane
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        desktop.add(usuario);
    }//GEN-LAST:event_btnCadastroUsuarioActionPerformed

    private void btnRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioClienteActionPerformed
// Relatorio de Clientes
        int confirmar = JOptionPane.showConfirmDialog(null, "Deseja emitir o Relátorio?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            // Imprimindo relatorio utilizando o framework JasperReport
            try {
                //Utilizando a Classe JasperPrint para fazer a impressão
                JasperPrint print = JasperFillManager.fillReport("C:\\PIM\\Relatorios\\Clientes.jasper", null, conexao);
                // Exibe o Relátorio utilizando a Classe JasperViewer
                JasperViewer.viewReport(print, false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } else {
        }

    }//GEN-LAST:event_btnRelatorioClienteActionPerformed

    private void btnRelatorioServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioServActionPerformed
        // Relatorio de Serviços
        int confirmar = JOptionPane.showConfirmDialog(null, "Deseja emitir o Relátorio?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            // Imprimindo relatorio utilizando o framework JasperReport
            try {
                //Utilizando a Classe JasperPrint para fazer a impressão
                JasperPrint print = JasperFillManager.fillReport("C:\\PIM\\Relatorios\\Servicos.jasper", null, conexao);
                // Exibe o Relátorio utilizando a Classe JasperViewer
                JasperViewer.viewReport(print, false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        } else {
        }

    }//GEN-LAST:event_btnRelatorioServActionPerformed

    private void btnAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaSobreActionPerformed
// Tela Sobre
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);


    }//GEN-LAST:event_btnAjudaSobreActionPerformed

    private void btnOpSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpSairActionPerformed
// Caixa de Dialogo 
        int sair = JOptionPane.showConfirmDialog(null, "Deseja Sair do Sistema ? ", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_btnOpSairActionPerformed

    private void btnTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTecActionPerformed
// Abre o Form DemandaOrdem
        TelaDemandaOrdem demanda = new TelaDemandaOrdem();
        demanda.setVisible(true);
        desktop.add(demanda);

    }//GEN-LAST:event_btnTecActionPerformed

    private void btnOpTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpTrocarActionPerformed
        // Tela Logar 
        int trocar = JOptionPane.showConfirmDialog(null, "Deseja Trocar de Usuário ? ", "Atenção", JOptionPane.YES_NO_OPTION);
        if (trocar == JOptionPane.YES_OPTION) {
            this.dispose();
            TelaLogin login = new TelaLogin();
            login.setVisible(true);

        }
    }//GEN-LAST:event_btnOpTrocarActionPerformed

    private void btnCadastrarAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarAllActionPerformed
        //  

    }//GEN-LAST:event_btnCadastrarAllActionPerformed

    private void btnRelatoriosAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRelatoriosAllActionPerformed

    private void btnAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjudaActionPerformed

    private void btnOptionAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOptionAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JToggleButton btnAjuda;
    private javax.swing.JToggleButton btnAjudaSobre;
    public static javax.swing.JToggleButton btnCadastraOS;
    public static javax.swing.JToggleButton btnCadastrarAll;
    public static javax.swing.JToggleButton btnCadastroCliente;
    public static javax.swing.JToggleButton btnCadastroUsuario;
    private javax.swing.JToggleButton btnOpSair;
    private javax.swing.JToggleButton btnOpTrocar;
    public static javax.swing.JToggleButton btnOptionAll;
    public static javax.swing.JToggleButton btnRelatorioCliente;
    public static javax.swing.JToggleButton btnRelatorioServ;
    public static javax.swing.JToggleButton btnRelatoriosAll;
    public static javax.swing.JToggleButton btnTec;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblPerfil;
    public static javax.swing.JLabel lblUsuario;
    public static javax.swing.JPanel pnlCadastrar;
    public static javax.swing.JPanel pnlRelatorio;
    // End of variables declaration//GEN-END:variables

    public void aparencia() {
        // Definindo as cores da Janela e Botões
        //Janela
        this.getContentPane().setBackground(new Color(224,204,149));

        //Botões
        //Tecnico
        this.btnTec.setBackground(new Color(0, 0, 0, 0));
        //Cadastrar
        this.btnCadastrarAll.setBackground(new Color(0, 0, 0, 0));
        this.btnCadastroCliente.setBackground(new Color(0, 0, 0, 0));
        this.btnCadastraOS.setBackground(new Color(0, 0, 0, 0));
        this.btnCadastroUsuario.setBackground(new Color(0, 0, 0, 0));
        // Relatorios
        this.btnRelatoriosAll.setBackground(new Color(0, 0, 0, 0));
        this.btnRelatorioCliente.setBackground(new Color(0, 0, 0, 0));
        this.btnRelatorioServ.setBackground(new Color(0, 0, 0, 0));
        //Ajuda
        this.btnAjuda.setBackground(new Color(0, 0, 0, 0));
        this.btnAjudaSobre.setBackground(new Color(0, 0, 0, 0));
        //Opçoes
        this.btnOptionAll.setBackground(new Color(0, 0, 0, 0));
        this.btnOpTrocar.setBackground(new Color(0, 0, 0, 0));
        this.btnOpSair.setBackground(new Color(0, 0, 0, 0));
    }

}
