/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import CRUD.Controlador;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import dal.ModuloConexao;
import java.awt.Color;

public class TelaDemandaOrdem extends javax.swing.JInternalFrame implements Controlador {

    // variavel de conexão
    Connection conexao = null;
    //PreparedStatement e ResultSet são frameworks do pacote java.sql 
    // Prepara e executa as instruçoes SQL
    PreparedStatement pst = null;
    ResultSet rs = null;

   
    public TelaDemandaOrdem() {
        initComponents();
        conexao = ModuloConexao.conector();
        
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        this.getContentPane().setBackground(Color.WHITE);
        
        //Variavel com o nome do tecnico
        String nomeTec = TelaPrincipal.lblUsuario.getText();
        // Set na label tecnico com a variavel tecnico
        this.lblTecnicoBuscar.setText(nomeTec);
        // Cor variavel
        this.lblTecnicoBuscar.setForeground(new Color(153,68,72));
        
        
     
    }

    public void pesquisar() {
        String sql = "select os as Os,data_os as Data ,tipo as tipo,equipamento as Equipamento,problema as Problema,servico as Serviço,tecnico as Técnico,situacao as Situação,prioridade as Prioridade, valor as Valor,idcli as IdCliente from tbos where tecnico like?;" ;
        try {
            //Prepara a String declarada da variavel sql
            pst = conexao.prepareStatement(sql);
            /*passando o conteudo da caixa de pesquisa para o "?"
            atenção ao "%" - continuação da String sql
             */
            pst.setString(1, this.lblTecnicoBuscar.getText());
            // Executa a Query
            rs = pst.executeQuery();
            // Linha abaixo utiliza  a biblioteca rs2xml para preencher a tabela
            this.tblOrdemDeServicos.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }

    public void selecionarDaTabela() {
        //Passo os dados para os campos da pnl Dados
        int selecionar = this.tblOrdemDeServicos.getSelectedRow();
        this.txtOs.setText(this.tblOrdemDeServicos.getModel().getValueAt(selecionar, 0).toString());
        this.txtOsProblema.setText(this.tblOrdemDeServicos.getModel().getValueAt(selecionar, 4).toString());
        this.txtOsServico.setText(this.tblOrdemDeServicos.getModel().getValueAt(selecionar, 5).toString());
        this.txtOsValor.setText(this.tblOrdemDeServicos.getModel().getValueAt(selecionar, 9).toString());
        this.cbOsSituacao.setSelectedItem(this.tblOrdemDeServicos.getModel().getValueAt(selecionar, 7).toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdemDeServicos = new javax.swing.JTable();
        txtOs = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblTecnicoBuscar = new javax.swing.JLabel();
        btnListarDemanda = new javax.swing.JButton();
        lbl001 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOsProblema = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtOsServico = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtOsValor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbOsSituacao = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        pnlOs = new javax.swing.JPanel();
        pnlClienteOpera = new javax.swing.JPanel();
        btnOsAlterar = new javax.swing.JButton();
        pnlOs1 = new javax.swing.JPanel();
        pnlClienteOpera1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(1014, 630));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblOrdemDeServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOrdemDeServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdemDeServicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrdemDeServicos);

        txtOs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOs.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Nº OS");

        lblTecnicoBuscar.setBackground(new java.awt.Color(153, 68, 72));
        lblTecnicoBuscar.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lblTecnicoBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTecnicoBuscar.setText("Técnico");

        btnListarDemanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/pesquisar.png"))); // NOI18N
        btnListarDemanda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListarDemanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarDemandaActionPerformed(evt);
            }
        });

        lbl001.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        lbl001.setText("Olá,");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl001)
                        .addGap(18, 18, 18)
                        .addComponent(lblTecnicoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarDemanda, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtOs, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTecnicoBuscar)
                            .addComponent(lbl001)))
                    .addComponent(btnListarDemanda))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnListarDemanda.getAccessibleContext().setAccessibleDescription("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Problema");

        txtOsProblema.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Serviço");

        txtOsServico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Valor Total");

        txtOsValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOsValor.setText("00,00");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Situação");

        cbOsSituacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbOsSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aberto", "Orçamento Reprovado", "Aguardando Aprovação", "Aguardando Peças", "Abandonado", "Aguardando Retirada", "Fechada" }));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel11.setText("Verificar Ordem de Serviço");

        pnlOs.setBackground(new java.awt.Color(153, 68, 72));
        pnlOs.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlOsLayout = new javax.swing.GroupLayout(pnlOs);
        pnlOs.setLayout(pnlOsLayout);
        pnlOsLayout.setHorizontalGroup(
            pnlOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlOsLayout.setVerticalGroup(
            pnlOsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        pnlClienteOpera.setBackground(new java.awt.Color(255, 255, 255));

        btnOsAlterar.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        btnOsAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/update.png"))); // NOI18N
        btnOsAlterar.setPreferredSize(new java.awt.Dimension(45, 45));
        btnOsAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClienteOperaLayout = new javax.swing.GroupLayout(pnlClienteOpera);
        pnlClienteOpera.setLayout(pnlClienteOperaLayout);
        pnlClienteOperaLayout.setHorizontalGroup(
            pnlClienteOperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteOperaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOsAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        pnlClienteOperaLayout.setVerticalGroup(
            pnlClienteOperaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteOperaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnOsAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pnlOs1.setBackground(new java.awt.Color(153, 68, 72));
        pnlOs1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N

        javax.swing.GroupLayout pnlOs1Layout = new javax.swing.GroupLayout(pnlOs1);
        pnlOs1.setLayout(pnlOs1Layout);
        pnlOs1Layout.setHorizontalGroup(
            pnlOs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        pnlOs1Layout.setVerticalGroup(
            pnlOs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        pnlClienteOpera1.setBackground(new java.awt.Color(153, 68, 72));

        javax.swing.GroupLayout pnlClienteOpera1Layout = new javax.swing.GroupLayout(pnlClienteOpera1);
        pnlClienteOpera1.setLayout(pnlClienteOpera1Layout);
        pnlClienteOpera1Layout.setHorizontalGroup(
            pnlClienteOpera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        pnlClienteOpera1Layout.setVerticalGroup(
            pnlClienteOpera1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel13.setText("Preencha os Dados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlClienteOpera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbOsSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOsValor, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(134, 134, 134))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtOsServico, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtOsProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlOs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlOs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlClienteOpera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel11))
                    .addComponent(pnlClienteOpera1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlOs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlClienteOpera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtOsProblema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtOsServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtOsValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cbOsSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        setBounds(0, 0, 1014, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void tblOrdemDeServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdemDeServicosMouseClicked
        // Metodo selecionarDaTabela
        selecionarDaTabela();
    }//GEN-LAST:event_tblOrdemDeServicosMouseClicked

    private void btnOsAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsAlterarActionPerformed
        // Metodo alterar
        alterar();
    }//GEN-LAST:event_btnOsAlterarActionPerformed

    private void btnListarDemandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarDemandaActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja listar Ordem de serviço? ", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
             pesquisar();
        }
       
    }//GEN-LAST:event_btnListarDemandaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarDemanda;
    private javax.swing.JButton btnOsAlterar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbOsSituacao;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl001;
    private javax.swing.JLabel lblTecnicoBuscar;
    private javax.swing.JPanel pnlClienteOpera;
    private javax.swing.JPanel pnlClienteOpera1;
    private javax.swing.JPanel pnlOs;
    private javax.swing.JPanel pnlOs1;
    private javax.swing.JTable tblOrdemDeServicos;
    private javax.swing.JTextField txtOs;
    private javax.swing.JTextField txtOsProblema;
    private javax.swing.JTextField txtOsServico;
    private javax.swing.JTextField txtOsValor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void adicionar() {
    }

    @Override
    public void consultar() {
    }

    @Override
    public void alterar() {
        String sql = "update tbos set problema=?,servico=?,situacao=?,valor=? where os=?";

        try {
            //prepara a String(comando do banco)definida na varivel sql 
            pst = conexao.prepareStatement(sql);
            pst.setString(1, this.txtOsProblema.getText());
            pst.setString(2, this.txtOsServico.getText());
            pst.setString(3, this.cbOsSituacao.getSelectedItem().toString());
            // replace troca o ponto por virgula
            pst.setString(4, this.txtOsValor.getText().replace(",", "."));
            pst.setString(5, this.txtOs.getText());

            //Validar os campos obrigatorios
            if ((this.txtOsServico.getText().isEmpty())
                    || (this.txtOsProblema.getText().isEmpty())
                    || (this.txtOsValor.getText().isEmpty())
                    || (this.cbOsSituacao.getSelectedItem().equals(""))) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos Obrigatórios *");

                // Apos validar - executa 
            } else {
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Ordem de Serviço Alterada com Sucesso");

                    //Limpa os campos
                    
                    this.txtOsProblema.setText(null);
                    this.txtOsServico.setText(null);
                    this.txtOsValor.setText(null);
                    this.cbOsSituacao.setSelectedItem("Aberto");

                  

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    @Override
    public void deletar() {
    }

}
